// Sample event data
const sampleEvents = [
    {
        id: 1,
        title: "Tech Conference 2025: AI Revolution",
        date: "2025-02-15",
        time: "09:00",
        location: "San Francisco",
        type: "conference",
        category: "technology",
        price: 299,
        description: "Join leading AI experts and innovators as they discuss the future of artificial intelligence and its impact on various industries. Learn about cutting-edge research, practical applications, and ethical considerations.",
        image: "https://images.pexels.com/photos/2608517/pexels-photo-2608517.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: true,
        popular: true,
        tags: ["AI", "Machine Learning", "Innovation"]
    },
    {
        id: 2,
        title: "UX Design Workshop: Creating Inclusive Experiences",
        date: "2025-01-20",
        time: "14:00",
        location: "Online",
        type: "workshop",
        category: "design",
        price: 0,
        description: "Learn how to design accessible and inclusive user experiences that work for everyone. This hands-on workshop covers accessibility guidelines, inclusive design principles, and practical implementation strategies.",
        image: "https://images.pexels.com/photos/196644/pexels-photo-196644.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["UX", "Accessibility", "Inclusive Design"]
    },
    {
        id: 3,
        title: "Business Growth Strategies Seminar",
        date: "2025-01-25",
        time: "10:30",
        location: "New York",
        type: "seminar",
        category: "business",
        price: 150,
        description: "Discover proven strategies for scaling your business in today's competitive market. Industry leaders will share insights on customer acquisition, retention strategies, and sustainable growth models.",
        image: "https://images.pexels.com/photos/3184360/pexels-photo-3184360.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: true,
        popular: true,
        tags: ["Growth", "Strategy", "Entrepreneurship"]
    },
    {
        id: 4,
        title: "Digital Marketing Bootcamp",
        date: "2025-02-01",
        time: "09:00",
        location: "Online",
        type: "workshop",
        category: "marketing",
        price: 199,
        description: "Master the fundamentals of digital marketing in this comprehensive bootcamp. Cover SEO, social media marketing, content strategy, email marketing, and analytics to boost your online presence.",
        image: "https://images.pexels.com/photos/265087/pexels-photo-265087.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: true,
        tags: ["SEO", "Social Media", "Content Marketing"]
    },
    {
        id: 5,
        title: "Health & Wellness Summit",
        date: "2025-02-10",
        time: "08:00",
        location: "Toronto",
        type: "conference",
        category: "health",
        price: 0,
        description: "A comprehensive summit focusing on holistic health approaches, mental wellness, nutrition, and fitness. Expert speakers will share the latest research and practical tips for maintaining a healthy lifestyle.",
        image: "https://images.pexels.com/photos/3822621/pexels-photo-3822621.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["Wellness", "Mental Health", "Nutrition"]
    },
    {
        id: 6,
        title: "Networking Night: Tech Professionals",
        date: "2025-01-18",
        time: "18:00",
        location: "San Francisco",
        type: "networking",
        category: "technology",
        price: 25,
        description: "Connect with fellow tech professionals in an informal networking environment. Great opportunity to share experiences, find mentors, discover job opportunities, and build lasting professional relationships.",
        image: "https://images.pexels.com/photos/1181396/pexels-photo-1181396.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["Networking", "Tech", "Career"]
    },
    {
        id: 7,
        title: "Sustainable Business Practices Workshop",
        date: "2025-01-30",
        time: "13:00",
        location: "London",
        type: "workshop",
        category: "business",
        price: 120,
        description: "Learn how to implement sustainable practices in your business operations. Topics include environmental responsibility, sustainable supply chain management, and green marketing strategies.",
        image: "https://images.pexels.com/photos/3184292/pexels-photo-3184292.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["Sustainability", "Environment", "CSR"]
    },
    {
        id: 8,
        title: "Advanced JavaScript Webinar",
        date: "2025-01-22",
        time: "16:00",
        location: "Online",
        type: "webinar",
        category: "technology",
        price: 0,
        description: "Deep dive into advanced JavaScript concepts including closures, prototypes, async programming, and modern ES6+ features. Perfect for developers looking to enhance their JavaScript skills.",
        image: "https://images.pexels.com/photos/4164418/pexels-photo-4164418.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: true,
        tags: ["JavaScript", "Programming", "Web Development"]
    },
    {
        id: 9,
        title: "Creative Design Thinking Session",
        date: "2025-02-05",
        time: "11:00",
        location: "New York",
        type: "workshop",
        category: "design",
        price: 85,
        description: "Explore innovative design thinking methodologies to solve complex problems creatively. Interactive session covering ideation techniques, prototyping, and user-centered design approaches.",
        image: "https://images.pexels.com/photos/3184465/pexels-photo-3184465.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["Design Thinking", "Innovation", "Creativity"]
    },
    {
        id: 10,
        title: "Financial Planning for Entrepreneurs",
        date: "2025-02-20",
        time: "14:30",
        location: "Toronto",
        type: "seminar",
        category: "business",
        price: 175,
        description: "Essential financial planning strategies for entrepreneurs and small business owners. Learn about budgeting, cash flow management, investment planning, and tax optimization strategies.",
        image: "https://images.pexels.com/photos/3184339/pexels-photo-3184339.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: true,
        popular: false,
        tags: ["Finance", "Planning", "Investment"]
    },
    {
        id: 11,
        title: "Content Creation Masterclass",
        date: "2025-01-28",
        time: "15:00",
        location: "Online",
        type: "workshop",
        category: "marketing",
        price: 99,
        description: "Master the art of creating engaging content across different platforms. Learn about storytelling, visual design, video production, and content strategy that drives engagement and conversions.",
        image: "https://images.pexels.com/photos/3184394/pexels-photo-3184394.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: true,
        tags: ["Content", "Storytelling", "Social Media"]
    },
    {
        id: 12,
        title: "Mindfulness and Productivity Retreat",
        date: "2025-02-08",
        time: "09:30",
        location: "London",
        type: "workshop",
        category: "health",
        price: 0,
        description: "Discover how mindfulness practices can enhance your productivity and overall well-being. This retreat combines meditation techniques with practical productivity strategies for a balanced lifestyle.",
        image: "https://images.pexels.com/photos/3822622/pexels-photo-3822622.jpeg?auto=compress&cs=tinysrgb&w=400",
        featured: false,
        popular: false,
        tags: ["Mindfulness", "Productivity", "Well-being"]
    }
];

// Initialize events data
let allEvents = [...sampleEvents];
let currentEvents = [...allEvents];
let eventsPerPage = 6;
let currentPage = 1;